#pragma once

static const char* scancode1_kc_strings[] = {
    "INVALID",
    "ESC",
    "1", "2", "3", "4", "5", "6", "7", "8", "9", "0",
    "-", "=", "\b", "\t",
    "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P",
    "[", "]", "\n", "LCTRL",
    "A", "S", "D", "F", "G", "H", "J", "K", "L",
    ";", "'", "`", "LSHIFT", "\\",
    "Z", "X", "C", "V", "B", "N", "M", ",", ".", "/",
    "RSHIFT", "KP_*", "LALT", " ", "CAPSLOCK",
    "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10",
    "NUMLOCK", "SCROLLLOCK", // this two particular lines  
    "KP_7", "KP_8", "KP_9", "KP_-",
    "KP_4", "KP_5", "KP_6", "KP_+",
    "KP_1", "KP_2", "KP_3", "KP_0", "KP_.",
    "F11", "F12",
    "MUL_PREV", "MUL_NEXT",
    "KP_ENTER",
    "RCTRL", "MUL_MUTE", "MUL_CALC", "MUL_PLAY", "MUL_STOP", "MUL_VOLDOWN", "MUL_VOLUP", "MUL_WWWHOME",
    "KP_/", "ALTGR", "HOME", "UP", "PAGE_UP",
    "LEFT", "RIGHT", "END", "DOWN", "PAGE_DOWN", "INSERT", "DEL",
    "LGUI", "RGUI", "APPS",
    "ACPI_POWER", "ACPI_SLEEP", "ACPI_WAKE",
    "MUL_SEARCH", "MUL_FAV", "MUL_REFRESH", "MUL_STOP",
    "MUL_FORWARD", "MUL_BACK", "MUL_MYPC", "MUL_EMAIL", "MUL_MEDIASEL",
    "PRNTSCR", "PAUSE"
};

typedef enum
{
    KC_INVALID = 0,

    KC_ESC,
    KC_1,
    KC_2,
    KC_3,
    KC_4,
    KC_5,
    KC_6,
    KC_7,
    KC_8,
    KC_9,
    KC_0,
    KC_MINUS,
    KC_EQ,
    KC_BACKSPACE,
    KC_TAB,
    KC_Q,
    KC_W,
    KC_E,
    KC_R,
    KC_T,
    KC_Y,
    KC_U,
    KC_I,
    KC_O,
    KC_P,
    KC_OPEN_SQUAREBRACKET,
    KC_CLOSE_SQUAREBRACKET,
    KC_ENTER,
    KC_LCTRL,
    KC_A,
    KC_S,
    KC_D,
    KC_F,
    KC_G,
    KC_H,
    KC_J,
    KC_K,
    KC_L,
    KC_SEMICOLON,
    KC_SINGLEQUOTE,
    KC_BACKTICK,
    KC_LSHIFT,
    KC_BACKSLASH,
    KC_Z,
    KC_X,
    KC_C,
    KC_V,
    KC_B,
    KC_N,
    KC_M,
    KC_COMMA,
    KC_DOT,
    KC_SLASH,
    KC_RSHIFT,
    KC_KP_STAR,
    KC_LALT,
    KC_SPACE,
    KC_CAPSLOCK,
    KC_F1,
    KC_F2,
    KC_F3,
    KC_F4,
    KC_F5,
    KC_F6,
    KC_F7,
    KC_F8,
    KC_F9,
    KC_F10,
    KC_NUMLOCK,
    KC_SCROLLLOCK,
    KC_KP_7,
    KC_KP_8,
    KC_KP_9,
    KC_KP_MINUS,
    KC_KP_4,
    KC_KP_5,
    KC_KP_6,
    KC_KP_PLUS,
    KC_KP_1,
    KC_KP_2,
    KC_KP_3,
    KC_KP_0,
    KC_KP_DOT,

    KC_F11,
    KC_F12,

    KC_MUL_PREVIOUS_TRACK,
    KC_MUL_NEXT_TRACK,

    KC_KP_ENTER,

    KC_RCTRL,
    KC_MUL_MUTE,
    KC_MUL_CALC,
    KC_MUL_PLAY,
    KC_MUL_STOP,
    KC_MUL_VOLDOWN,
    KC_MUL_VOLUP,
    KC_MUL_WWWHOME,
    KC_KP_SLASH,
    KC_ALTGR,
    KC_HOME,
    KC_CUR_UP,
    KC_PAGE_UP,
    KC_CUR_LEFT,
    KC_CUR_RIGHT,
    KC_END,
    KC_CUR_DOWN,
    KC_PAGE_DOWN,
    KC_INSERT,
    KC_DEL,
    KC_LGUI,
    KC_RGUI,
    KC_APPS,
    KC_ACPI_POWER,
    KC_ACPI_SLEEP,
    KC_ACPI_WAKE,
    KC_MUL_WWWSEARCH,
    KC_MUL_WWWFAV,
    KC_MUL_WWWREFRESH,
    KC_MUL_WWWSTOP,
    KC_MUL_WWWFORWARD,
    KC_MUL_WWWBACK,
    KC_MUL_MYPC,
    KC_MUL_EMAIL,
    KC_MUL_MEDIASEL,
    KC_PRNTSCR,
    KC_PAUSEBREAK,

    KC_ENUM_SIZE
} scancode2_to_keycode;